// Auto-generated by LibreLane
module chip_core(
`ifdef USE_POWER_PINS
  inout VDD,
  inout VSS,
`endif
  input clk,
  input rst_n,
  input input_in,
  output input_pu,
  output input_pd,
  input[9:0] bidir_in,
  output[9:0] bidir_out,
  output[9:0] bidir_oe,
  output[9:0] bidir_cs,
  output[9:0] bidir_sl,
  output[9:0] bidir_ie,
  output[9:0] bidir_pu,
  output[9:0] bidir_pd,
  inout[3:0] analog
);
endmodule
