// Auto-generated by LibreLane
module wrapper(
`ifdef USE_POWER_PINS
  inout VDD,
  inout VSS,
`endif
  input clk,
  input analog_readout_input,
  output analog_readout_output,
  output analog_error_x_output,
  output analog_error_y_output,
  input rst_n,
  input spi_cs_n,
  input spi_sclk,
  input spi_mosi,
  output spi_miso,
  output spi_miso_oe,
  output move_en_x,
  output dir_x,
  output move_en_y,
  output dir_y,
  output mems_drv_x,
  output mems_drv_y
);
endmodule
