meta:
  version: 3
  flow: Classic

DESIGN_NAME: chip_core

VERILOG_FILES:
  - dir::../src/chip_core.sv

CLOCK_PORT: clk
CLOCK_NET: clk
CLOCK_PERIOD: 200   # 5 MHz

# Let the tool size the core
FP_SIZING: relative
FP_CORE_UTIL: 30
PL_TARGET_DENSITY_PCT: 55

# Synthesis strategy
SYNTH_STRATEGY: "AREA 0"

# Route congestion
GRT_ALLOW_CONGESTION: true

# Optional: keep power nets (good practice)
VDD_NETS:
  - VDD
GND_NETS:
  - VSS