// Auto-generated by LibreLane
module signal_processor(
`ifdef USE_POWER_PINS
  inout VDD,
  inout VSS,
`endif
  input clk,
  input rst_n,
  input soft_rst_n,
  input comp_raw,
  input latch_phase90,
  input latch_phase270,
  output latch_phase90_ack,
  output latch_phase270_ack,
  output dir,
  output move_en,
  output jitter_flag,
  output[1:0] phase_state,
  output[3:0] votes_in_phase,
  output[3:0] votes_out_phase
);
endmodule
