/* Generated by Yosys 0.67 (git sha1 2d1509d1b, Release, GNU /usr/bin/c++ 13.3.0) */

module state_machine(clk, rst_n, boot_complete, cfg_done, phase_offset_imported, cal_start, cal_done, cal_timeout, read_en, soft_rst, state_o);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input boot_complete;
  wire boot_complete;
  input cfg_done;
  wire cfg_done;
  input phase_offset_imported;
  wire phase_offset_imported;
  output cal_start;
  wire cal_start;
  input cal_done;
  wire cal_done;
  input cal_timeout;
  wire cal_timeout;
  output read_en;
  wire read_en;
  input soft_rst;
  wire soft_rst;
  output [2:0] state_o;
  wire [2:0] state_o;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _18_ (
    .I(soft_rst),
    .ZN(_03_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _19_ (
    .I(state_o[1]),
    .ZN(_04_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _20_ (
    .I(cfg_done),
    .ZN(_05_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _21_ (
    .A1(state_o[0]),
    .A2(_04_),
    .A3(state_o[2]),
    .ZN(cal_start)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _22_ (
    .A1(state_o[1]),
    .A2(state_o[2]),
    .Z(_06_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _23_ (
    .A1(state_o[1]),
    .A2(state_o[2]),
    .ZN(_07_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _24_ (
    .A1(state_o[0]),
    .A2(_06_),
    .A3(_07_),
    .ZN(read_en)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _25_ (
    .A1(cal_timeout),
    .A2(cal_done),
    .ZN(_08_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or4_1 _26_ (
    .A1(state_o[0]),
    .A2(_04_),
    .A3(state_o[2]),
    .A4(_08_),
    .Z(_09_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _27_ (
    .A1(state_o[0]),
    .A2(boot_complete),
    .B(_07_),
    .ZN(_10_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _28_ (
    .A1(state_o[0]),
    .A2(_07_),
    .Z(_11_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _29_ (
    .A1(_09_),
    .A2(_10_),
    .B1(_11_),
    .B2(_05_),
    .ZN(_12_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _30_ (
    .A1(state_o[0]),
    .A2(_12_),
    .B(_03_),
    .ZN(_13_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _31_ (
    .A1(state_o[0]),
    .A2(_12_),
    .B(_13_),
    .ZN(_00_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _32_ (
    .A1(state_o[1]),
    .A2(_12_),
    .ZN(_14_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _33_ (
    .A1(phase_offset_imported),
    .A2(_11_),
    .ZN(_15_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _34_ (
    .A1(cal_start),
    .A2(_11_),
    .B(_15_),
    .ZN(_16_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi211_1 _35_ (
    .A1(_12_),
    .A2(_16_),
    .B(_14_),
    .C(soft_rst),
    .ZN(_01_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _36_ (
    .A1(state_o[2]),
    .A2(_12_),
    .ZN(_17_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi211_1 _37_ (
    .A1(_12_),
    .A2(_15_),
    .B(_17_),
    .C(soft_rst),
    .ZN(_02_)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _38_ (
    .CLK(clk),
    .D(_00_),
    .Q(state_o[0]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _39_ (
    .CLK(clk),
    .D(_01_),
    .Q(state_o[1]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _40_ (
    .CLK(clk),
    .D(_02_),
    .Q(state_o[2]),
    .RN(rst_n)
  );
endmodule
