// Auto-generated by LibreLane
module chip_top(
`ifdef USE_POWER_PINS
  inout VDD,
  inout VSS,
`endif
  inout clk_PAD,
  inout rst_n_PAD,
  inout input_PAD,
  inout[19:0] bidir_PAD,
  inout[59:0] analog_PAD
);
endmodule
