// Auto-generated by LibreLane
module wave_controller(
`ifdef USE_POWER_PINS
  inout VDD,
  inout VSS,
`endif
  input clk,
  input rst_n,
  input soft_rst_n,
  input[15:0] cfg_f_MEMS_fcw,
  input[20:0] cfg_phase0_offset,
  input[20:0] cfg_phase90_offset,
  input[20:0] cfg_phase270_offset,
  input cfg_done,
  output cal_done,
  output cal_timeout,
  input cal_start,
  input comp,
  output latch_phase90,
  output latch_phase270,
  input latch_phase90_ack,
  input latch_phase270_ack,
  output mems_drv,
  output ref_wave,
  output[7:0] delay_wave_cycle,
  output[20:0] raw_edge1,
  output[20:0] raw_edge2,
  output[20:0] raw_edge3,
  output cal_dir,
  output[20:0] cal_phase0_offset,
  output[20:0] cal_phase90_offset,
  output[20:0] cal_phase270_offset,
  output latch_error
);
endmodule
