/* Generated by Yosys 0.66 (git sha1 86f2ddebc-dirty, g++ 13.3.0-6ubuntu2~24.04.1 -fPIC -O3) */

module gf180mcu_ef_io__bi_t(CS, SL, IE, OE, PU, PD, A, ANA, PDRV0, PDRV1, PAD, Y, DVDD, DVSS, VDD, VSS);
  input CS;
  wire CS;
  input SL;
  wire SL;
  input IE;
  wire IE;
  input OE;
  wire OE;
  input PU;
  wire PU;
  input PD;
  wire PD;
  input A;
  wire A;
  inout ANA;
  wire ANA;
  input PDRV0;
  wire PDRV0;
  input PDRV1;
  wire PDRV1;
  inout PAD;
  wire PAD;
  output Y;
  wire Y;
  inout DVDD;
  wire DVDD;
  inout DVSS;
  wire DVSS;
  inout VDD;
  wire VDD;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_io__asig_5p0(ASIG5V, DVDD, DVSS, VDD, VSS);
  inout ASIG5V;
  wire ASIG5V;
  inout DVDD;
  wire DVDD;
  inout DVSS;
  wire DVSS;
  inout VDD;
  wire VDD;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_io__bi_24t(CS, SL, IE, OE, PU, PD, A, PAD, Y, DVDD, DVSS, VDD, VSS);
  input CS;
  wire CS;
  input SL;
  wire SL;
  input IE;
  wire IE;
  input OE;
  wire OE;
  input PU;
  wire PU;
  input PD;
  wire PD;
  input A;
  wire A;
  inout PAD;
  wire PAD;
  output Y;
  wire Y;
  inout DVDD;
  wire DVDD;
  inout DVSS;
  wire DVSS;
  inout VDD;
  wire VDD;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_io__bi_t(CS, SL, IE, OE, PU, PD, A, PDRV0, PDRV1, PAD, Y, DVDD, DVSS, VDD, VSS);
  input CS;
  wire CS;
  input SL;
  wire SL;
  input IE;
  wire IE;
  input OE;
  wire OE;
  input PU;
  wire PU;
  input PD;
  wire PD;
  input A;
  wire A;
  input PDRV0;
  wire PDRV0;
  input PDRV1;
  wire PDRV1;
  inout PAD;
  wire PAD;
  output Y;
  wire Y;
  inout DVDD;
  wire DVDD;
  inout DVSS;
  wire DVSS;
  inout VDD;
  wire VDD;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_io__brk2(VSS);
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_io__brk5(VSS);
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_io__cor(DVDD, DVSS, VDD, VSS);
  inout DVDD;
  wire DVDD;
  inout DVSS;
  wire DVSS;
  inout VDD;
  wire VDD;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_io__dvdd(DVDD, DVSS, VSS);
  inout DVDD;
  wire DVDD;
  inout DVSS;
  wire DVSS;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_io__dvss(DVDD, DVSS, VDD);
  inout DVDD;
  wire DVDD;
  inout DVSS;
  wire DVSS;
  inout VDD;
  wire VDD;
endmodule

module gf180mcu_fd_io__fill1(DVDD, DVSS, VDD, VSS);
  inout DVDD;
  wire DVDD;
  inout DVSS;
  wire DVSS;
  inout VDD;
  wire VDD;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_io__fill10(DVDD, DVSS, VDD, VSS);
  inout DVDD;
  wire DVDD;
  inout DVSS;
  wire DVSS;
  inout VDD;
  wire VDD;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_io__fill5(DVDD, DVSS, VDD, VSS);
  inout DVDD;
  wire DVDD;
  inout DVSS;
  wire DVSS;
  inout VDD;
  wire VDD;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_io__fillnc(DVDD, DVSS, VDD, VSS);
  inout DVDD;
  wire DVDD;
  inout DVSS;
  wire DVSS;
  inout VDD;
  wire VDD;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_io__in_c(PU, PD, PAD, Y, DVDD, DVSS, VDD, VSS);
  input PU;
  wire PU;
  input PD;
  wire PD;
  input PAD;
  wire PAD;
  output Y;
  wire Y;
  inout DVDD;
  wire DVDD;
  inout DVSS;
  wire DVSS;
  inout VDD;
  wire VDD;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_io__in_s(PU, PD, PAD, Y, DVDD, DVSS, VDD, VSS);
  input PU;
  wire PU;
  input PD;
  wire PD;
  input PAD;
  wire PAD;
  output Y;
  wire Y;
  inout DVDD;
  wire DVDD;
  inout DVSS;
  wire DVSS;
  inout VDD;
  wire VDD;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_ws_io__dvdd(DVDD, DVSS, VSS);
  inout DVDD;
  wire DVDD;
  inout DVSS;
  wire DVSS;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_ws_io__dvss(DVDD, DVSS, VDD);
  inout DVDD;
  wire DVDD;
  inout DVSS;
  wire DVSS;
  inout VDD;
  wire VDD;
endmodule
