// Auto-generated by LibreLane
module state_machine(
`ifdef USE_POWER_PINS
  inout VDD,
  inout VSS,
`endif
  input clk,
  input rst_n,
  input boot_complete,
  input cfg_done,
  input phase_offset_imported,
  output cal_start,
  input cal_done,
  input cal_timeout,
  output read_en,
  input soft_rst,
  output[2:0] state_o
);
endmodule
